### ISSUE TITLE
Переезд на поддомен

### ISSUE THREAD

**Issue by yukisnowflake** [xfourteen/neppedapi-ts#2]
Отныне NeppedAPI работает на поддомене. Требуется переделать работу SDK для дальнейшей работы с API.
# Что требуется сделать?
Ранее чтобы обратиться к API, нужно было делать запрос на `neppedcord.top/api`. Теперь нужно делать запрос на `api.neppedcord.top` (без `/api`).

**Comment by phxnelxck** [comment]
Аккаунт автора давно неактивен. Владелец потерял к нему доступ.

**Comment by yukisnowflake** [comment]
> Аккаунт автора давно неактивен. Владелец потерял к нему доступ.

![image](https://user-images.githubusercontent.com/32297717/107845068-a3a9d500-6dfa-11eb-9b04-5d31c94530dc.png)
